import i18n from "../i18n";

const t = i18n.global.t;

const heroMap = {
  "040": {
    name: t("name_040"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/040.png",
    intro: t("intro_040"),
    avatar: require("../assets/avatar/0/040.jpg"),
  },
  "030": {
    name: t("name_031"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/030.png",
    intro: t("intro_031"),
    avatar: require("../assets/avatar/0/030.jpg"),
  },
  "031": {
    name: t("name_031"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/031.png",
    intro: t("intro_031"),
    avatar: require("../assets/avatar/0/031.jpg"),
  },
  "032": {
    name: t("name_032"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/032.png",
    intro: t("intro_032"),
    avatar: require("../assets/avatar/0/032.jpg"),
  },
  "033": {
    name: t("name_033"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/033.png",
    intro: t("intro_033"),
    avatar: require("../assets/avatar/0/033.jpg"),
  },
  "020": {
    name: t("name_020"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/020.png",
    intro: t("intro_020"),
    avatar: require("../assets/avatar/0/020.jpg"),
  },
  "021": {
    name: t("name_021"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/021.png",
    intro: t("intro_021"),
    avatar: require("../assets/avatar/0/021.jpg"),
  },
  "022": {
    name: t("name_022"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/022.png",
    intro: t("intro_022"),
    avatar: require("../assets/avatar/0/022.jpg"),
  },
  "023": {
    name: t("name_023"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/023.png",
    intro: t("intro_023"),
    avatar: require("../assets/avatar/0/023.jpg"),
  },
  "024": {
    name: t("name_024"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/024.png",
    intro: t("intro_024"),
    avatar: require("../assets/avatar/0/024.jpg"),
  },
  "010": {
    name: t("name_010"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/010.png",
    intro: t("intro_010"),
    avatar: require("../assets/avatar/0/010.jpg"),
  },
  "011": {
    name: t("name_011"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/011.png",
    intro: t("intro_011"),
    avatar: require("../assets/avatar/0/011.jpg"),
  },
  "012": {
    name: t("name_012"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/012.png",
    intro: t("intro_012"),
    avatar: require("../assets/avatar/0/012.jpg"),
  },
  "013": {
    name: t("name_013"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/013.png",
    intro: t("intro_013"),
    avatar: require("../assets/avatar/0/013.jpg"),
  },
  "014": {
    name: t("name_014"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/014.png",
    intro: "",
    avatar: require("../assets/avatar/0/014.jpg"),
  },
  "015": {
    name: t("name_015"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/0/015.png",
    intro: t("intro_014"),
    avatar: require("../assets/avatar/0/015.jpg"),
  },
  140: {
    name: t("name_140"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/140.png",
    intro: t("intro_140"),
    avatar: require("../assets/avatar/1/140.jpg"),
  },
  130: {
    name: t("name_130"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/130.png",
    intro: t("intro_130"),
    avatar: require("../assets/avatar/1/130.jpg"),
  },
  131: {
    name: t("name_131"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/131.png",
    intro: t("intro_131"),
    avatar: require("../assets/avatar/1/131.jpg"),
  },
  132: {
    name: t("name_132"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/132.png",
    intro: t("intro_132"),
    avatar: require("../assets/avatar/1/132.jpg"),
  },
  133: {
    name: t("name_133"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/133.png",
    intro: t("intro_133"),
    avatar: require("../assets/avatar/1/133.jpg"),
  },
  120: {
    name: t("name_120"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/120.png",
    intro: t("intro_120"),
    avatar: require("../assets/avatar/1/120.jpg"),
  },
  121: {
    name: t("name_121"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/121.png",
    intro: t("intro_121"),
    avatar: require("../assets/avatar/1/121.jpg"),
  },
  122: {
    name: t("name_122"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/122.png",
    intro: t("intro_122"),
    avatar: require("../assets/avatar/1/122.jpg"),
  },
  123: {
    name: t("name_123"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/123.png",
    intro: t("intro_123"),
    avatar: require("../assets/avatar/1/123.jpg"),
  },
  124: {
    name: t("name_124"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/124.png",
    intro: t("intro_124"),
    avatar: require("../assets/avatar/1/124.jpg"),
  },
  110: {
    name: t("name_110"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/110.png",
    intro: t("intro_110"),
    avatar: require("../assets/avatar/1/110.jpg"),
  },
  111: {
    name: t("name_111"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/111.png",
    intro: t("intro_111"),
    avatar: require("../assets/avatar/1/111.jpg"),
  },
  112: {
    name: t("name_112"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/112.png",

    intro: t("intro_112"),
    avatar: require("../assets/avatar/1/112.jpg"),
  },
  113: {
    name: t("name_113"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/113.png",
    intro: t("intro_113"),
    avatar: require("../assets/avatar/1/113.jpg"),
  },
  114: {
    name: t("name_114"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/114.png",
    intro: t("intro_114"),
    avatar: require("../assets/avatar/1/114.jpg"),
  },
  115: {
    name: t("name_115"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/1/115.png",
    intro: t("intro_115"),
    avatar: require("../assets/avatar/1/115.jpg"),
  },
  240: {
    name: t("name_240"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/240.png",
    intro: t("intro_240"),
    avatar: require("../assets/avatar/2/240.jpg"),
  },
  230: {
    name: t("name_230"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/230.png",
    intro: t("intro_230"),
    avatar: require("../assets/avatar/2/230.jpg"),
  },
  231: {
    name: t("name_231"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/231.png",
    intro: t("intro_231"),
    avatar: require("../assets/avatar/2/231.jpg"),
  },
  232: {
    name: t("name_232"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/232.png",
    intro: t("intro_232"),
    avatar: require("../assets/avatar/2/232.jpg"),
  },
  233: {
    name: t("name_233"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/233.png",
    intro: t("intro_233"),
    avatar: require("../assets/avatar/2/233.jpg"),
  },
  220: {
    name: t("name_220"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/220.png",
    intro: t("intro_220"),
    avatar: require("../assets/avatar/2/220.jpg"),
  },
  221: {
    name: t("name_221"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/221.png",
    intro: t("intro_221"),
    avatar: require("../assets/avatar/2/221.jpg"),
  },
  222: {
    name: t("name_222"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/222.png",
    intro: t("intro_222"),
    avatar: require("../assets/avatar/2/222.jpg"),
  },
  223: {
    name: t("name_223"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/223.png",
    intro: t("intro_223"),
    avatar: require("../assets/avatar/2/223.jpg"),
  },
  224: {
    name: t("name_224"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/224.png",
    intro: t("intro_224"),
    avatar: require("../assets/avatar/2/224.jpg"),
  },
  210: {
    name: t("name_210"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/210.png",
    intro: t("intro_210"),
    avatar: require("../assets/avatar/2/210.jpg"),
  },
  211: {
    name: t("name_211"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/211.png",
    intro: t("intro_211"),
    avatar: require("../assets/avatar/2/211.jpg"),
  },
  212: {
    name: t("name_212"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/212.png",
    intro: t("intro_212"),
    avatar: require("../assets/avatar/2/212.jpg"),
  },
  213: {
    name: t("name_213"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/213.png",
    intro: t("intro_213"),
    avatar: require("../assets/avatar/2/213.jpg"),
  },
  214: {
    name: t("name_214"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/214.png",
    intro: t("intro_214"),
    avatar: require("../assets/avatar/2/214.jpg"),
  },
  215: {
    name: t("name_215"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/2/215.png",
    intro: t("intro_215"),
    avatar: require("../assets/avatar/2/215.jpg"),
  },
  340: {
    name: t("name_340"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/340.png",
    intro: t("intro_340"),
    avatar: require("../assets/avatar/3/340.jpg"),
  },
  330: {
    name: t("name_330"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/330.png",
    intro: t("intro_330"),
    avatar: require("../assets/avatar/3/330.jpg"),
  },
  331: {
    name: t("name_331"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/331.png",
    intro: t("intro_331"),
    avatar: require("../assets/avatar/3/331.jpg"),
  },
  332: {
    name: t("name_332"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/332.png",
    intro: t("intro_332"),
    avatar: require("../assets/avatar/3/332.jpg"),
  },
  333: {
    name: t("name_333"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/333.png",
    intro: t("intro_333"),
    avatar: require("../assets/avatar/3/333.jpg"),
  },
  320: {
    name: t("name_320"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/320.png",
    intro: t("intro_320"),
    avatar: require("../assets/avatar/3/320.jpg"),
  },
  321: {
    name: t("name_321"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/321.png",
    intro: t("intro_321"),
    avatar: require("../assets/avatar/3/321.jpg"),
  },
  322: {
    name: t("name_322"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/322.png",
    intro: t("intro_322"),
    avatar: require("../assets/avatar/3/322.jpg"),
  },
  323: {
    name: t("name_323"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/323.png",
    intro: t("intro_323"),
    avatar: require("../assets/avatar/3/323.jpg"),
  },
  324: {
    name: t("name_324"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/324.png",
    intro: t("intro_324"),
    avatar: require("../assets/avatar/3/324.jpg"),
  },
  310: {
    name: t("name_310"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/310.png",
    intro: t("intro_310"),
    avatar: require("../assets/avatar/3/310.jpg"),
  },
  311: {
    name: t("name_311"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/311.png",
    intro: t("intro_311"),
    avatar: require("../assets/avatar/3/311.jpg"),
  },
  312: {
    name: t("name_312"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/312.png",
    intro: t("intro_312"),
    avatar: require("../assets/avatar/3/312.jpg"),
  },
  313: {
    name: t("name_313"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/313.png",
    intro: t("intro_313"),
    avatar: require("../assets/avatar/3/313.jpg"),
  },
  314: {
    name: t("name_314"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/314.png",
    intro: t("intro_314"),
    avatar: require("../assets/avatar/3/314.jpg"),
  },
  315: {
    name: t("name_315"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/3/315.png",
    intro: t("intro_315"),
    avatar: require("../assets/avatar/3/315.jpg"),
  },
  s0: {
    name: t("name_s0"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/s0.png",
    intro: t("name_s0"),
    avatar: require("../assets/avatar/4/s0.jpg"),
  },
  s1: {
    name: t("name_s1"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/s1.png",
    intro: t("name_s1"),
    avatar: require("../assets/avatar/4/s1.jpg"),
  },
  s2: {
    name: t("name_s2"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/s2.png",
    intro: t("name_s2"),
    avatar: require("../assets/avatar/4/s2.jpg"),
  },
  s3: {
    name: t("name_s3"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/s3.png",
    intro: t("name_s3"),
    avatar: require("../assets/avatar/4/s3.jpg"),
  },
  s4: {
    name: t("name_s4"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/s4.png",
    intro: t("name_s4"),
    avatar: require("../assets/avatar/4/s4.jpg"),
  },
  err: {
    name: t("name_err"),
    img: "https://cryptorich3.mypinata.cloud/ipfs/QmYcwx7pKcH9y9kFCwx2pswmvjGSFPLPDv2Ld8SovipH2h/rich/assets/cardImgs/hero/s1.png",
    intro: t("intro_err"),
    avatar: require("../assets/avatar/4/s4.jpg"),
  },
};

const getHeroInfo = (id, p) => {
  if (id[1] == 0) {
    return heroMap[`s${p}`];
  }
  return heroMap[id];
};

export default getHeroInfo;
